CREATE TABLE PetOwners (
	OwnerId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	OwnerName TEXT,
	OwnerPhone NUMERIC,
	HasExotic BOOLEAN
);

CREATE TABLE Cats (
	CatId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CatName TEXT,
	Color TEXT,
	OwnerId INT,
	FOREIGN KEY (OwnerId) REFERENCES PetOwners (OwnerId)

CREATE TABLE VetClinics (
	VetClinicId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ClinicName TEXT
);

CREATE TABLE VetClinicCustomers ()



